### ISSUE TITLE
Why using pgx? not pgxpool?

### ISSUE THREAD

**Issue by kokizzu** [edgedb/imdbench#64]
pgx is single connection
pgxpool is the connection pooling version of pgx (equal to database/sql that have built-in connection pool)

are other benchmarks also only have single connection to database?

https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool
https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool

**Comment by elprans** [comment]
All benchmarks use `N` connections to the database: each worker "thread" owns a connection.  There is no point in using pgxpool here as connections are not shared across goroutines.
